### ISSUE TITLE
Cleverbot API

### ISSUE THREAD

**Issue by Orkan-M** [lemon65/lemon_bot_discord#3]
Hey there, 

It seems the Cleverbot API went official. 
So I believe the cleverbot dependency for github went down. What do you think I should do? Go with the limited 5000 requests/month from the official website, or do you think there is an alternative?

**Comment by lemon65** [comment]
I would say go with a limited amount, and you might have to change the auth as well if they changed it. Sorry that it took so long to get back to you
.

**Comment by Orkan-M** [comment]
It's no problem, I figured out a way to do this. I really like your coding techniques. It has inspired me to make commands

**Comment by lemon65** [comment]
Thanks, that means alot to me :)
